<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-05T22:43:43 IST" name="Suite" finished-at="2022-05-05T22:44:34 IST" duration-ms="51099">
    <groups>
    </groups>
    <test started-at="2022-05-05T22:43:43 IST" name="Test" finished-at="2022-05-05T22:44:34 IST" duration-ms="51099">
      <class name="com.TestNG.Sample">
        <test-method is-config="true" signature="bc()[pri:0, instance:com.TestNG.Sample@37afeb11]" started-at="2022-05-05T22:43:43 IST" name="bc" finished-at="2022-05-05T22:44:00 IST" duration-ms="17474" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bc -->
        <test-method signature="contact()[pri:0, instance:com.TestNG.Sample@37afeb11]" started-at="2022-05-05T22:44:00 IST" name="contact" finished-at="2022-05-05T22:44:29 IST" duration-ms="28924" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contact -->
        <test-method signature="org()[pri:0, instance:com.TestNG.Sample@37afeb11]" started-at="2022-05-05T22:44:00 IST" name="org" finished-at="2022-05-05T22:44:24 IST" duration-ms="23972" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.TestNG.Sample.org(Sample.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- org -->
      </class> <!-- com.TestNG.Sample -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
